log_level: debug

team: 55
number_of_teams: 242
team_token: "" # Remember to edit the team token


team_format: "fd66:666:%d::2"

round_duration: 120
flag_alive: 5
flag_format: "FAUST_[A-Za-z0-9/+]{32}"

flagid_url: "2024.faustctf.net/competition/teams.json"

sub_protocol: "faust"
sub_limit: 1
#sub_interval: 5
sub_interval: 20
#sub_max_payload_size: 30
sub_max_payload_size: 5000
#sub_url: "http://172.31.207.108:8000"
sub_url: "submission.faustctf.net:666"
start_round: "2024-09-28 13:00:00" # "Y-m-d H:M:S"

database: "mongodb://mongo:27017"
