
services:
  
  mongo:
    image: mongo:5
    restart: always

  submitter:
    build: ./srcs/
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "5000:5000"

    volumes:
      # - ./srcs/:/app/ # DEVELOPEMENT
      - ./submitter.log:/app/submitter.log

